{
   "data":{
      "settings":[
         {
            "type":"title",
            "value":"FlyWeb"
         },
         {
            "type":"url",
            "value":"http:\/\/positifmobile.com\/flyweb\/demo"
         },
         {
            "type":"admob_id",
            "value":"ca-app-pub-8380185804726759~8970223218"
         },
         {
            "type":"admob_id_ios",
            "value":"ca-app-pub-8380185804726759~3245650098"
         },
         {
            "type":"admob_key_ad_banner",
            "value":"ca-app-pub-3940256099942544\/9214589741"
         },
         {
            "type":"admob_key_ad_interstitial",
            "value":"ca-app-pub-3940256099942544\/1033173712"
         },
         {
            "type":"admob_key_ad_banner_ios",
            "value":"ca-app-pub-3940256099942544\/2934735716"
         },
         {
            "type":"admob_key_ad_interstitial_ios",
            "value":"ca-app-pub-3940256099942544\/4411468910"
         },
         {
            "type":"admob_dealy",
            "value":"10000"
         },
         {
            "type":"navigatin_bar_style",
            "value":"center"
         },
         {
            "type":"left_button",
            "value":""
         },
         {
            "type":"right_button",
            "value":""
         },
         {
            "type":"loader",
            "value":"FoldingCube"
         },
         {
            "type":"loaderColor",
            "value":"#54a276"
         },
         {
            "type":"firstColor",
            "value":"#54a276"
         },
         {
            "type":"secondColor",
            "value":"#54a276"
         },
         {
            "type":"backgroundColor",
            "value":null
         },
         {
            "type":"logo",
            "value":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/settings\/settings_1.png"
         },
         {
            "type":"javascript",
            "value":"0"
         },
         {
            "type":"download_webview",
            "value":"0"
         },
         {
            "type":"permission_dialog",
            "value":"0"
         },
         {
            "type":"splach_screen",
            "value":"0"
         },
         {
            "type":"swipe_refresh",
            "value":"0"
         },
         {
            "type":"website_zoom",
            "value":"0"
         },
         {
            "type":"desktop_mode",
            "value":"0"
         },
         {
            "type":"full_screen",
            "value":"0"
         },
         {
            "type":"sub_title",
            "value":"Convert your Website to an App"
         },
         {
            "type":"logo_header",
            "value":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/settings\/logo_header_1.png"
         },
         {
            "type":"type_header",
            "value":"empty"
         },
         {
            "type":"about_us",
            "value":"FlyWeb is a universal convertor Web to App inspired by the Flutter framework, made by Google. It is the best solutions to convert your website to Android and iOS with just your URL.\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
         },
         {
            "type":"android_id",
            "value":"com.smartselwady.yallavamos"
         },
         {
            "type":"ios_id",
            "value":"com.smartselwady.yallavamos"
         },
         {
            "type":"onesignal_id",
            "value":"aae0693d-26da-4290-9903-c0b80cfd0b6f"
         },
         {
            "type":"onesignal_api_key",
            "value":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
         },
         {
            "type":"share",
            "value":"Download LiveSpot App \r\nThe Ultimate Video Player & Browser Without Mandatory Advertising\r\nhttps:\/\/play.google.com\/store\/apps\/details?id=com.smartselwady.livespot"
         },
         {
            "type":"list",
            "value":null
         },
         {
            "type":"ad_banner",
            "value":"false"
         },
         {
            "type":"ad_interstitial",
            "value":"false"
         },
         {
            "type":"pull_refresh",
            "value":"true"
         },
         {
            "type":"boarding",
            "value":"true"
         },
         {
            "type":"deeplink",
            "value":"yallavamos"
         },
         {
            "type":"tab_navigation_enable",
            "value":"true"
         },
         {
            "type":"colorTab",
            "value":"#0b0a0a"
         },
         {
            "type":"version_android",
            "value":"1.0.1"
         },
         {
            "type":"version_ios",
            "value":"1.0.1"
         },
         {
            "type":"version_app",
            "value":"version_app"
         },
         {
            "type":"purchase_code",
            "value":"0a1d6f57-7a47-4276-8f10-708723f438cf"
         },
         {
            "type":"customCss",
            "value":""
         },
         {
            "type":"customJavascript",
            "value":""
         },
         {
            "type":"floating_margin_bottom",
            "value":"1"
         },
         {
            "type":"floating_background_color",
            "value":"#4b8a95"
         },
         {
            "type":"floating_icon_color",
            "value":"#ffffff"
         },
         {
            "type":"floating_enable",
            "value":"0"
         },
         {
            "type":"floating_icon",
            "value":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/floating\/floating_icon.png"
         },
         {
            "type":"google_font",
            "value":"Cairo"
         },
         {
            "type":"tab_color_icon_active",
            "value":"#54a276"
         },
         {
            "type":"tab_color_icon_active_dark",
            "value":"#54a276"
         },
         {
            "type":"tab_color_icon_inactive",
            "value":"#bdbdbd"
         },
         {
            "type":"tab_color_icon_inactive_dark",
            "value":"#bdbdbd"
         },
         {
            "type":"tab_color_background",
            "value":"#ffffff"
         },
         {
            "type":"tab_color_background_dark",
            "value":"#ffffff"
         },
         {
            "type":"default_language",
            "value":"2"
         },
         {
            "type":"floating_background_color_dark",
            "value":"#000000"
         },
         {
            "type":"floating_icon_color_dark",
            "value":"#ffffff"
         },
         {
            "type":"tab_position",
            "value":"bottom"
         },
         {
            "type":"default_language_code",
            "value":"ar"
         },
         {
            "type":"splash_logo_width",
            "value":"150"
         },
         {
            "type":"splash_logo_height",
            "value":"150"
         },
         {
            "type":"iconColor",
            "value":"#ffffff"
         },
         {
            "type":"height_header",
            "value":"60"
         },
         {
            "type":"floating_type",
            "value":"circular"
         },
         {
            "type":"tab_type",
            "value":"regular"
         },
         {
            "type":"logo_drawer",
            "value":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/settings\/logo_drawer.png"
         },
         {
            "type":"logo_drawer_width",
            "value":"250"
         },
         {
            "type":"logo_drawer_height",
            "value":"70"
         },
         {
            "type":"iconColor_dark",
            "value":"#ffffff"
         },
         {
            "type":"tab_refresh",
            "value":"true"
         },
         {
            "type":"initial_dark_mode",
            "value":"false"
         }
      ],
      "menus":[
         
      ],
      "socials":[
         {
            "id":"1",
            "title":"\u0641\u064a\u0633\u0628\u0648\u0643",
            "link_url":"fb:\/\/page\/id_app",
            "id_app":"ahlawai.online",
            "icon":"social_item_1.png",
            "url":"https:\/\/www.facebook.com\/id_app",
            "status":"1",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/social\/social_item_1.png"
         },
         {
            "id":"2",
            "title":"\u064a\u0648\u062a\u064a\u0648\u0628",
            "link_url":"https:\/\/youtube.com\/id_app",
            "id_app":"@ahlawai.online",
            "icon":"social_item_2.png",
            "url":"https:\/\/www.youtube.com\/channel\/id_app",
            "status":"1",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/social\/social_item_2.png"
         },
         {
            "id":"4",
            "title":"\u0645\u0646\u0635\u0629 X",
            "link_url":"https:\/\/twitter.com\/id_app",
            "id_app":"ahlawai_online",
            "icon":"social_item_4.png",
            "url":"https:\/\/twitter.com\/id_app",
            "status":"1",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/social\/social_item_4.png"
         },
         {
            "id":"7",
            "title":"\u062a\u064a\u0643 \u062a\u0648\u0643",
            "link_url":"https:\/\/www.tiktok.com\/id_app",
            "id_app":"@ahlawai.online",
            "icon":"social_item_7.png",
            "url":"https:\/\/www.tiktok.com\/id_app",
            "status":"1",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/social\/social_item_7.png"
         },
         {
            "id":"8",
            "title":"\u0625\u0646\u0633\u062a\u062c\u0631\u0627\u0645",
            "link_url":"instagram:\/\/user?username=id_app",
            "id_app":"ahlawai.online",
            "icon":"social_item_8.png",
            "url":"https:\/\/www.instagram.com\/id_app",
            "status":"1",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/social\/social_item_8.png"
         },
         {
            "id":"9",
            "title":"\u062b\u0631\u064a\u062f\u0632",
            "link_url":"https:\/\/www.threads.net\/id_app",
            "id_app":"@ahlawai.online",
            "icon":"social_item_9.png",
            "url":"https:\/\/www.threads.net\/id_app",
            "status":"1",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/social\/social_item_9.png"
         }
      ],
      "leftNavigationIcon":{
         "id":"1",
         "icon":"icon_item_1.png",
         "title":"Side Menu",
         "value":"icon_menu",
         "type":"action",
         "url":"",
         "status":"1",
         "fixed":"1",
         "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/left_navigation_icon\/icon_item_1.png"
      },
      "rightNavigationIcon":{
         "id":"2",
         "icon":"icon_item_2.png",
         "title":"Reload Button",
         "value":"icon_reload",
         "type":"action",
         "url":"",
         "status":"1",
         "fixed":"1",
         "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/right_navigation_icon\/icon_item_2.png"
      },
	  "rightNavigationIconList":[
         {
            "id":"2",
			 "icon":"icon_item_2.png",
			 "title":"Reload Button",
			 "value":"icon_reload",
			 "type":"action",
			 "url":"",
			 "status":"1",
			 "fixed":"1",
			 "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/right_navigation_icon\/icon_item_2.png"
         }
      ],
      "splash":{
         "id":"1",
         "firstColor":"#54a276",
         "secondColor":"#54a276",
         "logo_splash":"logo_splash.png",
         "img_splash":"logo.gif",
         "enable_logo":"1",
         "enable_img":"0",
         "splash_logo_width":"125",
         "splash_logo_height":"75",
         "logo_splash_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/splash\/logo_splash.png",
         "img_splash_url":"https:\/\/yallavamos-app.smartselwady.org\/website\/logo.gif"
      },
      "userAgent":{
         "id":"1",
         "title":"Chrome",
         "value_android":"",
         "value_ios":"",
         "status":"0"
      },
      "tab":[
         {
            "icon":"tab_item_1.png",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/tab\/tab_item_1.png",
            "translation":[
               {
                  "id":"1",
                  "tab_id":"1",
                  "title":"News",
                  "url":"https:\/\/yallavamos-app.smartselwady.org\/website\/?page=news",
                  "lang":"en",
                  "status":"1"
               },
               {
                  "id":"3",
                  "tab_id":"1",
                  "title":"\u0627\u0644\u0623\u062e\u0628\u0627\u0631",
                  "url":"https:\/\/yallavamos-app.smartselwady.org\/website\/?page=news",
                  "lang":"ar",
                  "status":"1"
               }
            ]
         },
         {
			"icon":"tab_item_2.png",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/tab\/tab_item_2.png",
            "translation":[
               {
                  "id":"4",
                  "tab_id":"2",
                  "title":"Matches",
                  "url":"https:\/\/yallavamos-app.smartselwady.org\/website\/?page=matches",
                  "lang":"en",
                  "status":"1"
               },
               {
                  "id":"5",
                  "tab_id":"2",
                  "title":"\u0627\u0644\u0645\u0628\u0627\u0631\u064a\u0627\u062a",
                  "url":"https:\/\/yallavamos-app.smartselwady.org\/website\/?page=matches",
                  "lang":"ar",
                  "status":"1"
               }
            ]
         },
         {
            "icon":"tab_item_3.png",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/tab\/tab_item_3.png",
            "translation":[
               {
                  "id":"6",
                  "tab_id":"3",
                  "title":"Highlights",
                  "url":"https:\/\/yallavamos-app.smartselwady.org\/website\/?page=highlights",
                  "lang":"en",
                  "status":"1"
               },
               {
                  "id":"7",
                  "tab_id":"3",
                  "title":"\u0627\u0644\u0641\u064a\u062f\u064a\u0648\u0647\u0627\u062a",
                  "url":"https:\/\/yallavamos-app.smartselwady.org\/website\/?page=highlights",
                  "lang":"ar",
                  "status":"1"
               }
            ]
         },
         {
            "icon":"tab_item_4.png",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/tab\/tab_item_4.png",
            "translation":[
               {
                  "id":"8",
                  "tab_id":"4",
                  "title":"Live",
                  "url":"https:\/\/yallavamos-app.smartselwady.org\/website\/?page=live",
                  "lang":"en",
                  "status":"1"
               },
               {
                  "id":"9",
                  "tab_id":"4",
                  "title":"\u0627\u0644\u0642\u0646\u0648\u0627\u062a",
                  "url":"https:\/\/yallavamos-app.smartselwady.org\/website\/?page=live",
                  "lang":"ar",
                  "status":"1"
               }
            ]
         },
         
      ],
      "pages":[

      ],
      "sliders":[
         {
            "id":"1",
            "image":"boarding_item_1.png",
            "title":"\u0623\u062e\u0631 \u0627\u0644\u0623\u062e\u0628\u0627\u0631",
            "description":"\u062a\u062d\u062f\u064a\u062b\u0627\u062a \u0641\u0648\u0631\u064a\u0629 \u062d\u0648\u0644 \u0623\u062e\u0631 \u0627\u0644\u0623\u062e\u0628\u0627\u0631 \u0627\u0644\u0631\u064a\u0627\u0636\u064a\u0629  \u0628\u0645\u0627 \u0641\u064a \u0630\u0644\u0643 \u0627\u0644\u0627\u0646\u062a\u0642\u0627\u0644\u0627\u062a \u0627\u0644\u0625\u0635\u0627\u0628\u0627\u062a \u0648\u0627\u0644\u062a\u0635\u0631\u064a\u062d\u0627\u062a \u0627\u0644\u0631\u0633\u0645\u064a\u0629",
            "status":"1",
            "image_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/boarding\/boarding_item_1.png"
         },
         {
            "id":"2",
            "image":"boarding_item_2.png",
            "title":"\u062c\u062f\u0648\u0644 \u0648\u0646\u062a\u0627\u0626\u062c \u0627\u0644\u0645\u0628\u0627\u0631\u064a\u0627\u062a",
            "description":"\u0639\u0631\u0636 \u062a\u0641\u0627\u0635\u064a\u0644 \u0645\u0628\u0627\u0631\u064a\u0627\u062a \u0627\u0644\u0646\u0627\u062f\u064a \u0627\u0644\u0645\u0642\u0628\u0644\u0629 \u0648 \u062a\u063a\u0637\u064a\u0629 \u0634\u0627\u0645\u0644\u0629 \u0644\u0646\u062a\u0627\u0626\u062c \u0627\u0644\u0645\u0628\u0627\u0631\u064a\u0627\u062a \u0627\u0644\u0633\u0627\u0628\u0642\u0629\u060c \u0645\u0639 \u062a\u0641\u0627\u0635\u064a\u0644 \u0639\u0646 \u0627\u0644\u0623\u062f\u0627\u0621 \u0648\u0645\u0644\u062e\u0635\u0627\u062a \u0644\u0643\u0644 \u0645\u0628\u0627\u0631\u0627\u0629",
            "status":"1",
            "image_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/boarding\/boarding_item_2.png"
         },
         {
            "id":"3",
            "image":"boarding_item_3.png",
            "title":"\u062a\u0646\u0628\u064a\u0647\u0627\u062a \u0641\u0648\u0631\u064a\u0629",
            "description":"\u0625\u0634\u0639\u0627\u0631\u0627\u062a \u0645\u0628\u0627\u0634\u0631\u0629 \u0644\u0644\u0645\u0633\u062a\u062e\u062f\u0645\u064a\u0646 \u062d\u0648\u0644 \u0627\u0644\u0623\u062e\u0628\u0627\u0631 \u0627\u0644\u0639\u0627\u062c\u0644\u0629 \u0648\u0646\u062a\u0627\u0626\u062c \u0627\u0644\u0645\u0628\u0627\u0631\u064a\u0627\u062a",
            "status":"1",
            "image_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/boarding\/boarding_item_3.png"
         }
      ],
      "nativeApplication":[
         "facebook.com",
         "skype.com",
         "twitter.com",
         "whatsapp:\/\/",
         "snapchat.com",
         "messenger.com",
         "instagram.com",
         "linkedin.com",
         "market:\/\/",
         "truecaller:\/\/",
         "play.google.com",
         "mailto:",
         "youtube.com",
         "tel:",
         "share=telegram"
      ],
      "menudynamics":[
         {
            "id":"21",
            "type":"url",
            "label":"\u0633\u064a\u0627\u0633\u0629 \u0627\u0644\u062e\u0635\u0648\u0635\u064a\u0629",
            "url":"https:\/\/yallavamos-app.smartselwady.org\/website\/?page=policy",
            "icon":"menu_item_21.png",
            "base64":null,
            "status":"1",
            "parent_id":"0",
            "position":"0",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/menu\/menu_item_21.png",
            "translation":[
               
            ]
         },
         {
            "id":"7",
            "type":"share",
            "label":"",
            "url":"",
            "icon":"default.png",
            "base64":null,
            "status":"1",
            "parent_id":"0",
            "position":"1",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/menu\/default.png",
            "translation":[
               
            ]
         }
      ],
      "floating":[
         {
            "id":"1",
            "title":"Sale",
            "type":"url",
            "icon":"floating_item_1.png",
            "url":"http:\/\/positifmobile.com\/positifMobile\/flyweb\/demo\/deals.html",
            "background_color":"#7b50dc",
            "background_color_dark":"#ffffff",
            "icon_color":"#ffffff",
            "icon_color_dark":"#000000",
            "status":"1",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/floating\/floating_item_1.png",
            "translation":[
               {
                  "id":"12",
                  "floating_id":"1",
                  "title":"Sale",
                  "url":"http:\/\/positifmobile.com\/flyweb\/demo\/deals.html",
                  "lang":"en"
               },
               {
                  "id":"13",
                  "floating_id":"1",
                  "title":"\u062a\u062e\u0641\u064a\u0636\u0627\u062a",
                  "url":"http:\/\/positifmobile.com\/flyweb\/demo\/deals.html",
                  "lang":"ar"
               }
            ]
         },
         {
            "id":"2",
            "title":"Cart",
            "type":"url",
            "icon":"floating_item_2.png",
            "url":"http:\/\/positifmobile.com\/positifMobile\/flyweb\/demo\/cart.html",
            "background_color":"#7b50dc",
            "background_color_dark":"#ffffff",
            "icon_color":"#ffffff",
            "icon_color_dark":"#000000",
            "status":"1",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/floating\/floating_item_2.png",
            "translation":[
               {
                  "id":"16",
                  "floating_id":"2",
                  "title":"\u0625\u0634\u0639\u0627\u0631\u0627\u062a",
                  "url":"http:\/\/positifmobile.com\/flyweb\/demo",
                  "lang":"ar"
               },
               {
                  "id":"17",
                  "floating_id":"2",
                  "title":"Notifications",
                  "url":"http:\/\/positifmobile.com\/flyweb\/demo",
                  "lang":"en"
               }
            ]
         },
         {
            "id":"3",
            "title":"Settings",
            "type":"url",
            "icon":"floating_item_3.png",
            "url":"http:\/\/positifmobile.com\/positifMobile\/flyweb\/demo\/settings.html",
            "background_color":"#7b50dc",
            "background_color_dark":"#ffffff",
            "icon_color":"#ffffff",
            "icon_color_dark":"#000000",
            "status":"1",
            "icon_url":"https:\/\/smartdb.smartselwady.org\/\/flutter_apps\/\/YallaVamos\/images\/floating\/floating_item_3.png",
            "translation":[
               {
                  "id":"18",
                  "floating_id":"3",
                  "title":"Settings",
                  "url":"http:\/\/positifmobile.com\/flyweb\/demo\/settings.html",
                  "lang":"en"
               },
               {
                  "id":"19",
                  "floating_id":"3",
                  "title":"\u0625\u0639\u062f\u0627\u062f\u0627\u062a",
                  "url":"http:\/\/positifmobile.com\/flyweb\/demo\/settings.html",
                  "lang":"ar"
               }
            ]
         }
      ],
      "languages":[
         {
            "id":"1",
            "title":"English",
            "title_native":"English",
            "code":"US",
            "app_lang_code":"en",
            "rtl":"0",
            "status":"1",
            "translations":[
               {
                  "id":"1",
                  "lang":"en",
                  "lang_key":"home",
                  "lang_value":"Home"
               },
               {
                  "id":"2",
                  "lang":"en",
                  "lang_key":"share",
                  "lang_value":"Share"
               },
               {
                  "id":"3",
                  "lang":"en",
                  "lang_key":"about",
                  "lang_value":"About"
               },
               {
                  "id":"4",
                  "lang":"en",
                  "lang_key":"rate_us",
                  "lang_value":"Rate Us"
               },
               {
                  "id":"5",
                  "lang":"en",
                  "lang_key":"update_application",
                  "lang_value":"Update Application"
               },
               {
                  "id":"6",
                  "lang":"en",
                  "lang_key":"notification",
                  "lang_value":"Notification"
               },
               {
                  "id":"7",
                  "lang":"en",
                  "lang_key":"languages",
                  "lang_value":"Languages"
               },
               {
                  "id":"8",
                  "lang":"en",
                  "lang_key":"app_language",
                  "lang_value":"App Language"
               },
               {
                  "id":"9",
                  "lang":"en",
                  "lang_key":"select_your_preferred_languages",
                  "lang_value":"Select your preferred languages"
               },
               {
                  "id":"10",
                  "lang":"en",
                  "lang_key":"whoops",
                  "lang_value":"Whoops!"
               },
               {
                  "id":"11",
                  "lang":"en",
                  "lang_key":"no_internet_connection",
                  "lang_value":"No internet connection"
               },
               {
                  "id":"12",
                  "lang":"en",
                  "lang_key":"try_again",
                  "lang_value":"Try Again"
               },
               {
                  "id":"13",
                  "lang":"en",
                  "lang_key":"close_app",
                  "lang_value":"Close APP"
               },
               {
                  "id":"14",
                  "lang":"en",
                  "lang_key":"are_you_sure_want_to_quit_this_application",
                  "lang_value":"Are you sure want to quit this application ?"
               },
               {
                  "id":"15",
                  "lang":"en",
                  "lang_key":"ok",
                  "lang_value":"OK"
               },
               {
                  "id":"16",
                  "lang":"en",
                  "lang_key":"cancel",
                  "lang_value":"CANCEL"
               },
               {
                  "id":"17",
                  "lang":"en",
                  "lang_key":"change_theme",
                  "lang_value":"Change Theme"
               },
               {
                  "id":"18",
                  "lang":"en",
                  "lang_key":"customize_your_own_way",
                  "lang_value":"Customize your own way"
               },
               {
                  "id":"20",
                  "lang":"en",
                  "lang_key":"navigation_bar_style",
                  "lang_value":"Navigation bar style"
               },
               {
                  "id":"21",
                  "lang":"en",
                  "lang_key":"header_type",
                  "lang_value":"Header type"
               },
               {
                  "id":"22",
                  "lang":"en",
                  "lang_key":"left_button_option",
                  "lang_value":"Left Button Option"
               },
               {
                  "id":"23",
                  "lang":"en",
                  "lang_key":"right_button_option",
                  "lang_value":"Right Button Option"
               },
               {
                  "id":"24",
                  "lang":"en",
                  "lang_key":"color_gradient",
                  "lang_value":"Color Gradient"
               },
               {
                  "id":"25",
                  "lang":"en",
                  "lang_key":"color_solid",
                  "lang_value":"Color Solid"
               },
               {
                  "id":"26",
                  "lang":"en",
                  "lang_key":"loading_animation",
                  "lang_value":"Loading Animation"
               },
               {
                  "id":"27",
                  "lang":"en",
                  "lang_key":"back_to_home_page",
                  "lang_value":"Back to HomePage"
               },
               {
                  "id":"28",
                  "lang":"en",
                  "lang_key":"dark_mode",
                  "lang_value":"Dark mode"
               },
               {
                  "id":"29",
                  "lang":"en",
                  "lang_key":"light_mode",
                  "lang_value":"Light mode"
               },
               {
                  "id":"59",
                  "lang":"en",
                  "lang_key":"follow_us",
                  "lang_value":"Follow Us"
               },
               {
                  "id":"61",
                  "lang":"en",
                  "lang_key":"get_start",
                  "lang_value":"Get Start"
               },
               {
                  "id":"63",
                  "lang":"en",
                  "lang_key":"skip",
                  "lang_value":"Skip"
               }
            ]
         },
         {
            "id":"2",
            "title":"Arabic",
            "title_native":"Arabic",
            "code":"AR",
            "app_lang_code":"ar",
            "rtl":"1",
            "status":"1",
            "translations":[
               {
                  "id":"30",
                  "lang":"ar",
                  "lang_key":"home",
                  "lang_value":"\u0627\u0644\u0645\u0648\u0642\u0639 \u0627\u0644\u0631\u0633\u0645\u064a"
               },
               {
                  "id":"31",
                  "lang":"ar",
                  "lang_key":"share",
                  "lang_value":"\u0645\u0634\u0627\u0631\u0643\u0629 \u0627\u0644\u062a\u0637\u0628\u064a\u0642"
               },
               {
                  "id":"32",
                  "lang":"ar",
                  "lang_key":"about",
                  "lang_value":"\u0645\u0639\u0644\u0648\u0645\u0627\u062a \u0639\u0646\u0627"
               },
               {
                  "id":"33",
                  "lang":"ar",
                  "lang_key":"rate_us",
                  "lang_value":"\u0642\u064a\u0651\u0645 \u0627\u0644\u062a\u0637\u0628\u064a\u0642"
               },
               {
                  "id":"34",
                  "lang":"ar",
                  "lang_key":"update_application",
                  "lang_value":"\u062a\u062d\u062f\u064a\u062b \u0627\u0644\u062a\u0637\u0628\u064a\u0642"
               },
               {
                  "id":"35",
                  "lang":"ar",
                  "lang_key":"notification",
                  "lang_value":"\u062a\u0646\u0628\u064a\u0647\u0627\u062a"
               },
               {
                  "id":"36",
                  "lang":"ar",
                  "lang_key":"languages",
                  "lang_value":"\u062a\u063a\u064a\u064a\u0631 \u0627\u0644\u0644\u063a\u0629"
               },
               {
                  "id":"37",
                  "lang":"ar",
                  "lang_key":"app_language",
                  "lang_value":"\u0644\u063a\u0629 \u0627\u0644\u062a\u0637\u0628\u064a\u0642"
               },
               {
                  "id":"38",
                  "lang":"ar",
                  "lang_key":"select_your_preferred_languages",
                  "lang_value":"\u0627\u062e\u062a\u0631 \u0644\u063a\u062a\u0643 \u0627\u0644\u0645\u0641\u0636\u0644\u0629"
               },
               {
                  "id":"39",
                  "lang":"ar",
                  "lang_key":"whoops",
                  "lang_value":"\u0639\u0641\u0648\u064b\u0627!"
               },
               {
                  "id":"40",
                  "lang":"ar",
                  "lang_key":"no_internet_connection",
                  "lang_value":"\u0644\u0627 \u064a\u0648\u062c\u062f \u0627\u062a\u0635\u0627\u0644 \u0628\u0627\u0644\u0625\u0646\u062a\u0631\u0646\u062a"
               },
               {
                  "id":"41",
                  "lang":"ar",
                  "lang_key":"try_again",
                  "lang_value":"\u062d\u0627\u0648\u0644 \u0645\u062c\u062f\u062f\u0627"
               },
               {
                  "id":"42",
                  "lang":"ar",
                  "lang_key":"close_app",
                  "lang_value":"\u0623\u063a\u0644\u0642 \u0627\u0644\u062a\u0637\u0628\u064a\u0642"
               },
               {
                  "id":"43",
                  "lang":"ar",
                  "lang_key":"are_you_sure_want_to_quit_this_application",
                  "lang_value":"\u0647\u0644 \u062a\u0631\u064a\u062f \u0628\u0627\u0644\u062a\u0623\u0643\u064a\u062f \u0627\u063a\u0644\u0627\u0642 \u0647\u0630\u0627 \u0627\u0644\u062a\u0637\u0628\u064a\u0642\u061f"
               },
               {
                  "id":"44",
                  "lang":"ar",
                  "lang_key":"ok",
                  "lang_value":"\u062d\u0633\u0646\u0627"
               },
               {
                  "id":"45",
                  "lang":"ar",
                  "lang_key":"cancel",
                  "lang_value":"\u0625\u0644\u063a\u0627\u0621"
               },
               {
                  "id":"46",
                  "lang":"ar",
                  "lang_key":"change_theme",
                  "lang_value":"\u063a\u064a\u0631 \u0627\u0644\u062e\u0644\u0641\u064a\u0629"
               },
               {
                  "id":"47",
                  "lang":"ar",
                  "lang_key":"customize_your_own_way",
                  "lang_value":"\u062a\u062e\u0635\u064a\u0635 \u0637\u0631\u064a\u0642\u062a\u0643 \u0627\u0644\u062e\u0627\u0635\u0629"
               },
               {
                  "id":"49",
                  "lang":"ar",
                  "lang_key":"navigation_bar_style",
                  "lang_value":"\u0646\u0645\u0637 \u0634\u0631\u064a\u0637 \u0627\u0644\u062a\u0646\u0642\u0644"
               },
               {
                  "id":"50",
                  "lang":"ar",
                  "lang_key":"header_type",
                  "lang_value":"\u0634\u0631\u064a\u0637 \u0627\u0644\u0631\u0623\u0633"
               },
               {
                  "id":"51",
                  "lang":"ar",
                  "lang_key":"left_button_option",
                  "lang_value":"\u062e\u064a\u0627\u0631 \u0627\u0644\u0632\u0631 \u0627\u0644\u0623\u064a\u0633\u0631"
               },
               {
                  "id":"52",
                  "lang":"ar",
                  "lang_key":"right_button_option",
                  "lang_value":"\u062e\u064a\u0627\u0631 \u0627\u0644\u0632\u0631 \u0627\u0644\u0623\u064a\u0645\u0646"
               },
               {
                  "id":"53",
                  "lang":"ar",
                  "lang_key":"color_gradient",
                  "lang_value":"\u0627\u0644\u062a\u062f\u0631\u062c \u0627\u0644\u0644\u0648\u0646"
               },
               {
                  "id":"54",
                  "lang":"ar",
                  "lang_key":"color_solid",
                  "lang_value":"\u0644\u0648\u0646 \u0648\u0627\u062d\u062f"
               },
               {
                  "id":"55",
                  "lang":"ar",
                  "lang_key":"loading_animation",
                  "lang_value":"\u0627\u0644\u0644\u0648\u062f\u0631"
               },
               {
                  "id":"56",
                  "lang":"ar",
                  "lang_key":"back_to_home_page",
                  "lang_value":"\u0627\u0644\u0639\u0648\u062f\u0629 \u0625\u0644\u0649 \u0627\u0644\u0635\u0641\u062d\u0629 \u0627\u0644\u0631\u0626\u064a\u0633\u064a\u0629"
               },
               {
                  "id":"57",
                  "lang":"ar",
                  "lang_key":"dark_mode",
                  "lang_value":"\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0627\u0643\u0646"
               },
               {
                  "id":"58",
                  "lang":"ar",
                  "lang_key":"light_mode",
                  "lang_value":"\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0641\u0627\u062a\u062d"
               },
               {
                  "id":"60",
                  "lang":"ar",
                  "lang_key":"follow_us",
                  "lang_value":"\u062a\u0627\u0628\u0639\u0646\u0627"
               },
               {
                  "id":"62",
                  "lang":"ar",
                  "lang_key":"get_start",
                  "lang_value":"\u0627\u0628\u062f\u0623"
               },
               {
                  "id":"64",
                  "lang":"ar",
                  "lang_key":"skip",
                  "lang_value":"\u062a\u062e\u0637\u0649"
               }
            ]
         }
      ],
      "about":[
         {
            "id":"1",
            "title":"Title",
            "url":"url",
            "icon":"about_item_1.png",
            "status":"1",
            "translation":[
               {
                  "id":"1",
                  "about_id":"1",
                  "title":"Title",
                  "description":"FlyWeb is a universal convertor Web to App inspired by the Flutter framework, made by Google. It is the best solutions to convert your website to Android and iOS with just your URL.",
                  "lang":"en",
                  "status":"1"
               },
               {
                  "id":"2",
                  "about_id":"1",
                  "title":"Title",
                  "description":"FlyWeb \u0639\u0628\u0627\u0631\u0629 \u0639\u0646 \u0628\u0631\u0646\u0627\u0645\u062c \u062a\u062d\u0648\u064a\u0644 \u0639\u0627\u0644\u0645\u064a \u0645\u0646 \u0627\u0644\u0648\u064a\u0628 \u0625\u0644\u0649 \u062a\u0637\u0628\u064a\u0642 \u0645\u0633\u062a\u0648\u062d\u0649 \u0645\u0646 \u0625\u0637\u0627\u0631 \u0639\u0645\u0644 Flutter \u0627\u0644\u0630\u064a \u062a\u0635\u0646\u0639\u0647 Google. \u0625\u0646\u0647\u0627 \u0623\u0641\u0636\u0644 \u0627\u0644\u062d\u0644\u0648\u0644 \u0644\u062a\u062d\u0648\u064a\u0644 \u0645\u0648\u0642\u0639 \u0627\u0644\u0648\u064a\u0628 \u0627\u0644\u062e\u0627\u0635 \u0628\u0643 \u0625\u0644\u0649 Android \u0648 iOS \u0628\u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0639\u0646\u0648\u0627\u0646 URL \u0627\u0644\u062e\u0627\u0635 \u0628\u0643 \u0641\u0642\u0637.",
                  "lang":"ar",
                  "status":"1"
               }
            ]
         }
      ],
      "applicationTranslation":[
         {
            "id":"1",
            "title":"",
            "sub_title":"",
            "url":"https:\/\/yalla-vamos.online\/",
            "lang":"en",
            "status":"1"
         },
         {
            "id":"10",
            "title":"",
            "sub_title":"",
            "url":"https:\/\/yalla-vamos.online\/",
            "lang":"ar",
            "status":"1"
         }
      ]
   }
}